SELECT A.ID, B.FISH_NAME, A.LENGTH AS LENGTH
FROM FISH_INFO A LEFT JOIN FISH_NAME_INFO B ON A.FISH_TYPE = B.FISH_TYPE
    
    JOIN (SELECT MAX(LENGTH) AS LENGTH, A.FISH_TYPE
            FROM FISH_INFO A, FISH_NAME_INFO B
            WHERE A.FISH_TYPE = B.FISH_TYPE
            GROUP BY FISH_NAME) C ON C.FISH_TYPE = A.FISH_TYPE AND C.LENGTH = A.LENGTH

GROUP BY B.FISH_NAME
ORDER BY A.ID